# Config file for Paper Mario NTSC 1.0 Recompilation.
# Based on Zelda64Recomp's Majora's Mask configuration file: https://github.com/Zelda64Recomp/Zelda64Recomp/blob/dev/us.rev1.toml.

[input]
entrypoint = 0x80080000
# Paths are relative to the location of this config file.
output_func_path = "RecompiledFuncs"
relocatable_sections_path = "overlays.paper_mario_usa_rev1.txt"
symbols_file_path = "paper_mario_usa_rev1.syms.toml"
rom_file_path = "rom/paper_mario_usa_rev1.z64"
